### ISSUE TITLE
License unspecified?

### ISSUE THREAD

**Issue by lowsfer** [rmsalinas/fbow#10]
What is the license term of fbow? Could you clarify?

**Comment by lawfx** [comment]
Hello @rmsalinas , can we get an answer on this license issue? Thanks.

**Comment by lawfx** [comment]
For anyone that might stumble upon this issue and didn't notice the README, this 
[commit](https://github.com/rmsalinas/fbow/commit/f897fff260ed5a2c4a8347802749c4d58c48bce6) states the license is MIT now.
