### ISSUE TITLE
Different vocabularies generated from same data

### ISSUE THREAD

**Issue by dukeNashor** [rmsalinas/fbow#24]
I tested fbow on same data for several times. It is worth noticing that different instances operating on the same data generated different vocabularies, while dbow3 generated the exact same vocabulary. is this normal?

**Comment by dukeNashor** [comment]
After some debugging, i noticed that the feature points in initial cluster may (almost always, in my case) duplicate; after changing the initial cluster selection part, everything worked fine.

**Comment by RashidLadj** [comment]
Hi @dukeNashor 

I can't quite understand the problem, I took a look at your repository but you haven't updated it on git, can you tell me where exactly is the problem?

Thank you.

**Comment by dukeNashor** [comment]
> Hi @dukeNashor
> 
> I can't quite understand the problem, I took a look at your repository but you haven't updated it on git, can you tell me where exactly is the problem?
> 
> Thank you.

nvm, the fbow's implementation for choosing the initial cluster centers is different from dbow's, which leads to the fact that different runs of fbow generate different vocabularies.
