### ISSUE TITLE
compile error on windows x64

### ISSUE THREAD

**Issue by hjl240** [rmsalinas/fbow#3]
Can it run on windows x64?
I compile the code on Visual Studio 2015, but it compile error.

**Comment by rmsalinas** [comment]
should work now

**Comment by hjl240** [comment]
Unfortunately, I compile it again,  but it still compile error.

**Comment by mshafiei** [comment]
I fixed the compile errors. Now I run it with few test images, fbow_create_voc_step0.exe runs successfully. but fbow_create_voc_step1.exe gives seg fault right after printing "Creating a 10^6 vocabulary". Any idea why?
