### ISSUE TITLE
Compiling on ARM64 architecture

### ISSUE THREAD

**Issue by mmitjansc** [rmsalinas/fbow#37]
Hello @rmsalinas and @shinsumicco,

It seems this project hasn't had any update in many years, but I hope you can help me with this small issue.

For what I've seen, the CMakeLists.txt file contemplates compiling with several architectures (ARM included), but then cpu.h and fbow.h/cpp don't offer any alternative to compile under ARM64. Is there any easy way to enable this? 

Thanks!

**Comment by MikiyaShibuya** [comment]
I have a solution (but it's sloppy) for the problem.
Please add `add_compile_definitions(FBOW_ANDROID=ON)` to your root CMakeLists.txt and replace all `__ANDROID__` macro to `FBOW_ANDROID`.

(If you using installed FBoW in the other project, you should add the same line `add_compile_definitions(...)` in its CMakelists.txt)

**Comment by mmitjansc** [comment]
Might be sloppy, but this solution worked like a charm, thank you!

Now I'm curious as to why it worked. I'm new in multi-processor compiling, so I'll keep digging a bit. But so far it works :)

**Comment by lockingball** [comment]
i cannot find immintrin.h ,that seems like g++7.5 for arm have not this .h file ,could you tell me how to fix it ,thank you!!!!

**Comment by mmitjansc** [comment]
Hi lockingball,
You should replace all your `#include <immintrin.h>` in your code by `#include <arm_neon.h>`.

**Comment by biggiantpigeon** [comment]
> arm_neon.h

I think you still need to change all the accelerating instruction to NEON to speed up for arm64?
